# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
cards = Card.create([
  {name: '2D', value: 2, suit: "D"},
  {name: '3D', value: 3, suit: "D"},
  {name: '4D', value: 4, suit: "D"},
  {name: '5D', value: 5, suit: "D"},
  {name: '6D', value: 6, suit: "D"},
  {name: '7D', value: 7, suit: "D"},
  {name: '8D', value: 8, suit: "D"},
  {name: '9D', value: 9, suit: "D"},
  {name: '10D', value: 10, suit: "D"},
  {name: 'JD', value: 11, suit: "D"},
  {name: 'QD', value: 12, suit: "D"},
  {name: 'KD', value: 13, suit: "D"},
  {name: 'AD', value: 14, suit: "D"},
  {name: '2C', value: 2, suit: "C"},
  {name: '3C', value: 3, suit: "C"},
  {name: '4C', value: 4, suit: "C"},
  {name: '5C', value: 5, suit: "C"},
  {name: '6C', value: 6, suit: "C"},
  {name: '7C', value: 7, suit: "C"},
  {name: '8C', value: 8, suit: "C"},
  {name: '9C', value: 9, suit: "C"},
  {name: '10C', value: 10, suit: "C"},
  {name: 'JC', value: 11, suit: "C"},
  {name: 'QC', value: 12, suit: "C"},
  {name: 'KC', value: 13, suit: "C"},
  {name: 'AC', value: 14, suit: "C"},
  {name: '2H', value: 2, suit: "H"},
  {name: '3H', value: 3, suit: "H"},
  {name: '4H', value: 4, suit: "H"},
  {name: '5H', value: 5, suit: "H"},
  {name: '6H', value: 6, suit: "H"},
  {name: '7H', value: 7, suit: "H"},
  {name: '8H', value: 8, suit: "H"},
  {name: '9H', value: 9, suit: "H"},
  {name: '10H', value: 10, suit: "H"},
  {name: 'JH', value: 11, suit: "H"},
  {name: 'QH', value: 12, suit: "H"},
  {name: 'KH', value: 13, suit: "H"},
  {name: 'AH', value: 14, suit: "H"},
  {name: '2S', value: 2, suit: "S"},
  {name: '3S', value: 3, suit: "S"},
  {name: '4S', value: 4, suit: "S"},
  {name: '5S', value: 5, suit: "S"},
  {name: '6S', value: 6, suit: "S"},
  {name: '7S', value: 7, suit: "S"},
  {name: '8S', value: 8, suit: "S"},
  {name: '9S', value: 9, suit: "S"},
  {name: '10S', value: 10, suit: "S"},
  {name: 'JS', value: 11, suit: "S"},
  {name: 'QS', value: 12, suit: "S"},
  {name: 'KS', value: 13, suit: "S"},
  {name: 'AS', value: 14, suit: "S"},
  ])
